//! Shape-aware shard planning for the VeriLLM BF16 traces.
//!
//! A planner unit is deliberately a semantic unit supplied by the caller (for example, one
//! complete output column or one complete attention head). The planner never cuts inside that
//! unit. It packs as many equal contiguous units as possible while respecting every BF16 chip's
//! row limit and a conservative combined main/preprocessed trace-area limit.

use crate::chips::bf16::{
    BF16_ADD_SUB_COLS, BF16_ADD_SUB_PREPROCESSED_COLS, BF16_DIV_COLS, BF16_DIV_PREPROCESSED_COLS,
    BF16_MUL_COLS, BF16_MUL_PREPROCESSED_COLS, BF16_UNARY_COLS, BF16_UNARY_PREPROCESSED_COLS,
    NUM_BF16_ADD_SUB_EVENTS_PER_ROW, NUM_BF16_MUL_EVENTS_PER_ROW,
};

/// The default maximum height used by the full-size VeriLLM leaf proofs.
pub const DEFAULT_MAX_LOG_ROWS: usize = 19;

/// The Core-style upper bound used for the combined main and preprocessed trace area.
pub const DEFAULT_MAX_TRACE_AREA: usize = (1 << 28) + (1 << 27);

/// Space reserved for Memory, Poseidon2, the BF16 lookup table, and other non-arithmetic chips.
///
/// The arithmetic planner cannot know these rows without compiling the complete circuit. Full
/// proofs enforce [`DEFAULT_MAX_TRACE_AREA`] again against the exact proof shape before proving.
pub const DEFAULT_NON_ARITHMETIC_AREA_RESERVE: usize = 1 << 25;

/// BF16 events emitted by one indivisible semantic unit.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct Bf16EventsPerUnit {
    pub mul: usize,
    pub add_sub: usize,
    pub unary: usize,
    pub div: usize,
}

/// Limits used while packing natural units into one leaf proof.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ShardLimits {
    pub max_log_rows: usize,
    pub max_trace_area: usize,
    pub non_arithmetic_area_reserve: usize,
}

impl ShardLimits {
    #[must_use]
    pub const fn full() -> Self {
        Self {
            max_log_rows: DEFAULT_MAX_LOG_ROWS,
            max_trace_area: DEFAULT_MAX_TRACE_AREA,
            non_arithmetic_area_reserve: DEFAULT_NON_ARITHMETIC_AREA_RESERVE,
        }
    }

    #[must_use]
    pub const fn max_rows(self) -> usize {
        1 << self.max_log_rows
    }
}

/// The estimated BF16 portion of one leaf trace.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct Bf16TraceEstimate {
    pub mul_rows: usize,
    pub add_sub_rows: usize,
    pub unary_rows: usize,
    pub div_rows: usize,
    pub arithmetic_trace_area: usize,
    pub estimated_trace_area: usize,
}

impl Bf16TraceEstimate {
    #[must_use]
    pub const fn max_rows(self) -> usize {
        let lhs = if self.mul_rows > self.add_sub_rows { self.mul_rows } else { self.add_sub_rows };
        let rhs = if self.unary_rows > self.div_rows { self.unary_rows } else { self.div_rows };
        if lhs > rhs {
            lhs
        } else {
            rhs
        }
    }
}

/// A uniform plan. Equal shard widths let every leaf reuse one program and one proving key.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct NaturalShardPlan {
    pub total_units: usize,
    pub units_per_shard: usize,
    pub shard_count: usize,
    pub estimate: Bf16TraceEstimate,
    pub limits: ShardLimits,
}

const fn padded_rows(events: usize, lanes: usize) -> usize {
    if events == 0 {
        0
    } else {
        events.div_ceil(lanes).next_multiple_of(32)
    }
}

/// Estimate the BF16 trace generated by `units` complete semantic units.
#[must_use]
pub fn estimate_bf16_trace(
    events: Bf16EventsPerUnit,
    units: usize,
    limits: ShardLimits,
) -> Bf16TraceEstimate {
    assert!(units > 0, "a leaf shard must contain at least one semantic unit");
    let mul_rows = padded_rows(events.mul.checked_mul(units).unwrap(), NUM_BF16_MUL_EVENTS_PER_ROW);
    let add_sub_rows =
        padded_rows(events.add_sub.checked_mul(units).unwrap(), NUM_BF16_ADD_SUB_EVENTS_PER_ROW);
    let unary_rows = padded_rows(events.unary.checked_mul(units).unwrap(), 1);
    let div_rows = padded_rows(events.div.checked_mul(units).unwrap(), 1);
    let arithmetic_trace_area = mul_rows * (BF16_MUL_COLS + BF16_MUL_PREPROCESSED_COLS)
        + add_sub_rows * (BF16_ADD_SUB_COLS + BF16_ADD_SUB_PREPROCESSED_COLS)
        + unary_rows * (BF16_UNARY_COLS + BF16_UNARY_PREPROCESSED_COLS)
        + div_rows * (BF16_DIV_COLS + BF16_DIV_PREPROCESSED_COLS);
    Bf16TraceEstimate {
        mul_rows,
        add_sub_rows,
        unary_rows,
        div_rows,
        arithmetic_trace_area,
        estimated_trace_area: arithmetic_trace_area + limits.non_arithmetic_area_reserve,
    }
}

/// Pack equal contiguous semantic units into one leaf.
///
/// The selected width must divide `total_units`; this deliberately trades a small amount of
/// packing efficiency for one circuit shape and one reusable proving key across all leaves.
#[must_use]
pub fn plan_uniform_natural_shards(
    total_units: usize,
    events: Bf16EventsPerUnit,
    limits: ShardLimits,
) -> NaturalShardPlan {
    assert!(total_units > 0, "a stage must contain at least one semantic unit");
    let mut largest_fitting = 0;
    for units in 1..=total_units {
        let estimate = estimate_bf16_trace(events, units, limits);
        if estimate.max_rows() <= limits.max_rows()
            && estimate.estimated_trace_area <= limits.max_trace_area
        {
            largest_fitting = units;
        }
    }
    assert!(largest_fitting > 0, "one semantic unit does not fit in the configured leaf limits");

    let units_per_shard = (1..=largest_fitting)
        .rev()
        .find(|units| total_units.is_multiple_of(*units))
        .expect("one always divides the number of semantic units");
    let estimate = estimate_bf16_trace(events, units_per_shard, limits);
    NaturalShardPlan {
        total_units,
        units_per_shard,
        shard_count: total_units / units_per_shard,
        estimate,
        limits,
    }
}

/// Plan a BF16 linear layer using a complete output column as the indivisible unit.
#[must_use]
pub fn plan_linear_output_columns(
    sequence_length: usize,
    input_width: usize,
    output_width: usize,
    unary_events_per_output: usize,
    limits: ShardLimits,
) -> NaturalShardPlan {
    assert!(sequence_length > 0);
    assert!(input_width > 0);
    assert!(output_width > 0);
    let events = Bf16EventsPerUnit {
        mul: sequence_length * input_width,
        add_sub: sequence_length * (input_width - 1),
        unary: sequence_length * unary_events_per_output,
        div: 0,
    };
    plan_uniform_natural_shards(output_width, events, limits)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn full_linear_stages_choose_natural_output_column_widths() {
        let limits = ShardLimits::full();
        let c_proj = plan_linear_output_columns(30, 768, 768, 0, limits);
        assert_eq!((c_proj.units_per_shard, c_proj.shard_count), (256, 3));

        let expansion = plan_linear_output_columns(30, 768, 2304, 1, limits);
        assert_eq!((expansion.units_per_shard, expansion.shard_count), (256, 9));

        let projection = plan_linear_output_columns(30, 2304, 768, 0, limits);
        assert_eq!((projection.units_per_shard, projection.shard_count), (64, 12));
    }

    #[test]
    fn attention_head_is_already_a_full_natural_unit() {
        let events =
            Bf16EventsPerUnit { mul: 4_529_745, add_sub: 4_568_085, unary: 23_535, div: 525 };
        let plan = plan_uniform_natural_shards(12, events, ShardLimits::full());
        assert_eq!((plan.units_per_shard, plan.shard_count), (1, 12));
    }

    #[test]
    fn area_limit_can_cut_before_the_height_limit() {
        let limits = ShardLimits {
            max_log_rows: 19,
            max_trace_area: 100_000,
            non_arithmetic_area_reserve: 0,
        };
        let events = Bf16EventsPerUnit { mul: 1_200, ..Bf16EventsPerUnit::default() };
        let plan = plan_uniform_natural_shards(16, events, limits);
        assert!(plan.estimate.estimated_trace_area <= limits.max_trace_area);
        assert!(plan.units_per_shard < 16);
    }
}
